# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60d2bee24f0b8aa368d185efb3544001"
name = "pb-chat-git"
handle = "pb-chat-git"
application_url = "https://pb-chat-git.vercel.app"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://pb-chat-git.vercel.app/api/auth" ]

[pos]
embedded = false

[mcp.customer_authentication]
redirect_uris = [
  "https://pb-chat-git.vercel.app/callback"
]
